version: "3.9"

volumes:
  hardlopen-db:

services:
  uitslagen-server:
    image: nilsbebelaar/hardlopen-scanner:latest
    container_name: Hardlopen-scanner
    restart: always
    ports:
      - '5001:5000'
    expose:
      - '5000'
    environment:
      - FLASK_DEBUG=False
      - FLASK_TESTING=False
      - SQLALCHEMY_DATABASE_PATH=database/uitslag.sqlite
    volumes:
      - hardlopen-db:/home/uitslagen/database